%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/intern/OpenFoamToolchain/Simulation_Outputs/Simulation_new1/simpleFoam/postProcessing/forceCoeffs1/0/forceCoeffs.dat
%
% Auto-generated by MATLAB on 07-Jul-2021 17:13:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [10, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "Cm", "Cd", "Cl", "Clf", "Clr"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
if ~general.switchMAC
    forceCoeffs = readtable(append(directions.path.solver,'/postProcessing/forceCoeffs1/0/forceCoeffs.dat'), opts);
else
    forceCoeffs = readtable(append(directions.path.solver,'/postProcessing/forceCoeffs1/0/coefficient.dat'), opts);
end

%% Clear temporary variables
clear opts