%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/intern/OpenFoamToolchain/Simulation_Outputs/Simulation_new2/simpleFoam/postProcessing/yPlus1/0/yPlus.dat
%
% Auto-generated by MATLAB on 07-Jul-2021 17:23:40

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "patch", "min", "max", "average"];
opts.VariableTypes = ["double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "patch", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "patch", "EmptyFieldRule", "auto");

% Import the data

yPlus = readtable(append(directions.path.solver,'/postProcessing/yPlus1/0/yPlus.dat'), opts);


%% Clear temporary variables
clear opts